<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\CourseModule;
use App\Models\Test;
use App\Models\User;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $instructor = User::whereHas('roles', fn($q) => $q->where('name', 'professor'))->first()
            ?? User::first();

        $courses = [
            // Romanian courses
            [
                'title' => 'Interpretarea ECG în urgență',
                'description' => 'Curs intensiv pentru interpretarea ECG în contextul urgențelor cardiace.',
                'category' => 'cardiology',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 8,
                'max_participants' => 200,
                'prerequisites' => ['Noțiuni de bază ECG', 'Fiziologie cardiacă'],
                'learning_objectives' => [
                    'Identificarea ritmurilor letale',
                    'Recunoașterea STEMI/NSTEMI',
                    'Identificarea tulburărilor de conducere'
                ],
                'course_content' => [
                    'Bazele ECG', 'Aritmii', 'Sindroame coronariene', 'Cazuri clinice'
                ],
                'assessment_criteria' => ['Test final 30 întrebări', 'Studii de caz'],
                'certification_type' => 'cme',
                'cme_credits' => 8,
                'cpe_credits' => null,
                'price' => 0,
                'discount_percentage' => null,
                'status' => 'published',
                'start_date' => now()->addDays(7),
                'end_date' => now()->addDays(14),
                'registration_deadline' => now()->addDays(5),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => true,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['ECG','urgență','cardiologie'],
                'target_audience' => ['Rezidenți', 'Medici Urgență', 'Cardiologi'],
                'accreditation_body' => 'Colegiul Medicilor din România',
                'accreditation_number' => 'CME-2025-0001',
                'contact_hours' => 8,
                'practical_hours' => 2,
                'theory_hours' => 6,
            ],
            [
                'title' => 'Managementul pacientului cu diabet tip 2',
                'description' => 'Abordare modernă a îngrijirii pacientului cu DZ tip 2, cu accent pe rezultate clinice.',
                'category' => 'endocrinology',
                'difficulty_level' => 'beginner',
                'duration_hours' => 10,
                'max_participants' => 300,
                'prerequisites' => ['Bazele fiziologiei', 'Farmacologie de bază'],
                'learning_objectives' => [
                    'Algoritmi de tratament 2025',
                    'Medicație GLP-1/SGLT2',
                    'Management complicații'
                ],
                'course_content' => ['Diagnostic', 'Tratament', 'Complicații', 'Cazuri'],
                'assessment_criteria' => ['Test final', 'Mini-OSCE'],
                'certification_type' => 'cme',
                'cme_credits' => 10,
                'cpe_credits' => null,
                'price' => 199,
                'discount_percentage' => 20,
                'status' => 'published',
                'start_date' => now()->addDays(10),
                'end_date' => now()->addDays(25),
                'registration_deadline' => now()->addDays(9),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => false,
                'is_free' => false,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['diabet','metabolism','cme'],
                'target_audience' => ['Medici familie', 'Interniști', 'Rezidenți'],
                'accreditation_body' => 'CMR',
                'accreditation_number' => 'CME-2025-0002',
                'contact_hours' => 6,
                'practical_hours' => 2,
                'theory_hours' => 2,
            ],
            [
                'title' => 'Ventilație non-invazivă în BPOC acut',
                'description' => 'Curs practic despre utilizarea NIV în exacerbările BPOC.',
                'category' => 'emergency_medicine',
                'difficulty_level' => 'advanced',
                'duration_hours' => 6,
                'max_participants' => 100,
                'prerequisites' => ['Fiziologie respiratorie', 'Bazele ventilării'],
                'learning_objectives' => [
                    'Indicații și contraindicații NIV',
                    'Parametri NIV și titrare',
                    'Monitorizare și complicații'
                ],
                'course_content' => ['Fiziologie', 'Setări NIV', 'Cazuri'],
                'assessment_criteria' => ['Test final', 'Checklist practic'],
                'certification_type' => 'completion',
                'cme_credits' => 0,
                'cpe_credits' => 4,
                'price' => 149,
                'discount_percentage' => null,
                'status' => 'published',
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(26),
                'registration_deadline' => now()->addDays(18),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => false,
                'requires_approval' => true,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 2,
                'tags' => ['BPOC','NIV','urgență'],
                'target_audience' => ['ATI', 'Urgență', 'Pneumologie'],
                'accreditation_body' => null,
                'accreditation_number' => null,
                'contact_hours' => 4,
                'practical_hours' => 2,
                'theory_hours' => 0,
            ],
            [
                'title' => 'Sepsis: recunoaștere timpurie și bundle-uri',
                'description' => 'Managementul modern al sepsisului: recunoaștere timpurie, resuscitare, antibiotice, source control.',
                'category' => 'emergency_medicine',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 8,
                'max_participants' => 250,
                'prerequisites' => ['Fiziologie', 'Medicină internă de bază'],
                'learning_objectives' => [
                    'Implementarea Surviving Sepsis Campaign 2021',
                    'Resuscitare volemică țintită',
                    'Antibioterapie timpurie și optimizare'
                ],
                'course_content' => ['Definiții Sepsis-3', 'Hemodinamică', 'Antibiotice', 'Control focar'],
                'assessment_criteria' => ['Test final', 'Cazuri clinice'],
                'certification_type' => 'cme',
                'cme_credits' => 8,
                'cpe_credits' => 4,
                'price' => 249,
                'discount_percentage' => 10,
                'status' => 'published',
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(22),
                'registration_deadline' => now()->addDays(13),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => false,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['sepsis','antibiotice','urgență'],
                'target_audience' => ['Anestezie-ATI', 'Urgență', 'Medicină Internă'],
                'accreditation_body' => 'CMR',
                'accreditation_number' => 'CME-2025-0003',
                'contact_hours' => 6,
                'practical_hours' => 2,
                'theory_hours' => 0,
            ],
            [
                'title' => 'Management avansat al AVC ischemic 2025',
                'description' => 'Abordare multidisciplinară a pacientului cu AVC ischemic: tromboliză, trombectomie, neuroprotecție.',
                'category' => 'neurology',
                'difficulty_level' => 'advanced',
                'duration_hours' => 10,
                'max_participants' => 150,
                'prerequisites' => ['Neurologie de bază', 'Medicină de urgență'],
                'learning_objectives' => [
                    'Selecția pacienților pentru tromboliză/trombectomie',
                    'Management peri-procedural',
                    'Prevenție secundară optimă'
                ],
                'course_content' => ['Imaging', 'Intervențional', 'Post-AVC', 'Cazuri'],
                'assessment_criteria' => ['Test final', 'OSCE mini'],
                'certification_type' => 'cme',
                'cme_credits' => 12,
                'cpe_credits' => 4,
                'price' => 299,
                'discount_percentage' => 15,
                'status' => 'published',
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(27),
                'registration_deadline' => now()->addDays(10),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => false,
                'is_free' => false,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['neurologie','intervențional','cme'],
                'target_audience' => ['Neurologi', 'Urgență', 'ATI'],
                'accreditation_body' => 'CMR',
                'accreditation_number' => 'CME-2025-0004',
                'contact_hours' => 6,
                'practical_hours' => 2,
                'theory_hours' => 2,
            ],
            [
                'title' => 'POCUS pentru medicii de urgență',
                'description' => 'Ultrasonografie la pat pentru decizii rapide în urgență: FAST, plămân, cord.',
                'category' => 'radiology',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 12,
                'max_participants' => 80,
                'prerequisites' => ['Noțiuni ecografie', 'Anatomie'],
                'learning_objectives' => [
                    'Protocol FAST extins',
                    'Ecografie pulmonară și semne B/A',
                    'Focused Cardiac Ultrasound (FoCUS)'
                ],
                'course_content' => ['FAST', 'Lung US', 'FoCUS', 'Ateliere practice'],
                'assessment_criteria' => ['Test final', 'Evaluare practică'],
                'certification_type' => 'completion',
                'cme_credits' => 6,
                'cpe_credits' => 6,
                'price' => 499,
                'discount_percentage' => 0,
                'status' => 'published',
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(33),
                'registration_deadline' => now()->addDays(27),
                'language' => 'ro',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => false,
                'requires_approval' => true,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 2,
                'tags' => ['pocus','ecografie','urgență'],
                'target_audience' => ['Urgență', 'ATI', 'Medic familie'],
                'accreditation_body' => 'CMR',
                'accreditation_number' => 'CME-2025-0005',
                'contact_hours' => 8,
                'practical_hours' => 4,
                'theory_hours' => 0,
            ],

            // English courses
            [
                'title' => 'ECG Interpretation in Emergencies',
                'description' => 'Intensive course for ECG interpretation in cardiac emergencies.',
                'category' => 'cardiology',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 8,
                'max_participants' => 200,
                'prerequisites' => ['Basic ECG concepts', 'Cardiac physiology'],
                'learning_objectives' => [
                    'Identify life-threatening rhythms',
                    'Recognize STEMI/NSTEMI',
                    'Identify conduction disturbances'
                ],
                'course_content' => ['ECG basics', 'Arrhythmias', 'ACS', 'Clinical cases'],
                'assessment_criteria' => ['Final 30-question test', 'Case studies'],
                'certification_type' => 'cme',
                'cme_credits' => 8,
                'cpe_credits' => null,
                'price' => 0,
                'discount_percentage' => null,
                'status' => 'published',
                'start_date' => now()->addDays(7),
                'end_date' => now()->addDays(14),
                'registration_deadline' => now()->addDays(5),
                'language' => 'en',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => true,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['ECG','emergency','cardiology'],
                'target_audience' => ['Residents', 'EM physicians', 'Cardiologists'],
                'accreditation_body' => 'Romanian College of Physicians',
                'accreditation_number' => 'CME-2025-1001',
                'contact_hours' => 8,
                'practical_hours' => 2,
                'theory_hours' => 6,
            ],
            [
                'title' => 'Sepsis: Early Recognition and Bundle Care',
                'description' => 'Modern sepsis care: early recognition, resuscitation, timely antibiotics, source control.',
                'category' => 'emergency_medicine',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 8,
                'max_participants' => 250,
                'prerequisites' => ['Physiology', 'Basic Internal Medicine'],
                'learning_objectives' => [
                    'Implement Surviving Sepsis Campaign 2021',
                    'Targeted fluid resuscitation',
                    'Early antibiotics and optimization'
                ],
                'course_content' => ['Sepsis-3', 'Hemodynamics', 'Antibiotics', 'Source control'],
                'assessment_criteria' => ['Final test', 'Clinical cases'],
                'certification_type' => 'cme',
                'cme_credits' => 8,
                'cpe_credits' => 4,
                'price' => 249,
                'discount_percentage' => 10,
                'status' => 'published',
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(22),
                'registration_deadline' => now()->addDays(13),
                'language' => 'en',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => false,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['sepsis','antibiotics','emergency'],
                'target_audience' => ['Anesthesia-ICU', 'Emergency', 'Internal Medicine'],
                'accreditation_body' => 'Romanian College of Physicians',
                'accreditation_number' => 'CME-2025-1002',
                'contact_hours' => 6,
                'practical_hours' => 2,
                'theory_hours' => 0,
            ],
            [
                'title' => 'Advanced Ischemic Stroke Management 2025',
                'description' => 'Multidisciplinary management: thrombolysis, thrombectomy, neuroprotection.',
                'category' => 'neurology',
                'difficulty_level' => 'advanced',
                'duration_hours' => 10,
                'max_participants' => 150,
                'prerequisites' => ['Basic Neurology', 'Emergency Medicine'],
                'learning_objectives' => [
                    'Patient selection for thrombolysis/thrombectomy',
                    'Peri-procedural management',
                    'Optimal secondary prevention'
                ],
                'course_content' => ['Imaging', 'Interventional', 'Post-stroke', 'Cases'],
                'assessment_criteria' => ['Final test', 'Mini-OSCE'],
                'certification_type' => 'cme',
                'cme_credits' => 12,
                'cpe_credits' => 4,
                'price' => 299,
                'discount_percentage' => 15,
                'status' => 'published',
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(27),
                'registration_deadline' => now()->addDays(10),
                'language' => 'en',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => false,
                'is_free' => false,
                'requires_approval' => false,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 3,
                'tags' => ['neurology','interventional','cme'],
                'target_audience' => ['Neurologists', 'Emergency', 'ICU'],
                'accreditation_body' => 'Romanian College of Physicians',
                'accreditation_number' => 'CME-2025-1003',
                'contact_hours' => 6,
                'practical_hours' => 2,
                'theory_hours' => 2,
            ],
            [
                'title' => 'POCUS for Emergency Physicians',
                'description' => 'Bedside ultrasound for rapid decision-making: FAST, lung, cardiac.',
                'category' => 'radiology',
                'difficulty_level' => 'intermediate',
                'duration_hours' => 12,
                'max_participants' => 80,
                'prerequisites' => ['Ultrasound basics', 'Anatomy'],
                'learning_objectives' => [
                    'Extended FAST protocol',
                    'Lung ultrasound (A/B lines)',
                    'Focused Cardiac Ultrasound (FoCUS)'
                ],
                'course_content' => ['FAST', 'Lung US', 'FoCUS', 'Hands-on'],
                'assessment_criteria' => ['Final test', 'Practical assessment'],
                'certification_type' => 'completion',
                'cme_credits' => 6,
                'cpe_credits' => 6,
                'price' => 499,
                'discount_percentage' => 0,
                'status' => 'published',
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(33),
                'registration_deadline' => now()->addDays(27),
                'language' => 'en',
                'timezone' => 'Europe/Bucharest',
                'is_featured' => true,
                'is_free' => false,
                'requires_approval' => true,
                'completion_rate_threshold' => 80,
                'passing_score' => 70,
                'max_attempts' => 2,
                'tags' => ['pocus','ultrasound','emergency'],
                'target_audience' => ['Emergency', 'ICU', 'Family Medicine'],
                'accreditation_body' => 'Romanian College of Physicians',
                'accreditation_number' => 'CME-2025-1004',
                'contact_hours' => 8,
                'practical_hours' => 4,
                'theory_hours' => 0,
            ],
        ];

        foreach ($courses as $c) {
            $course = Course::updateOrCreate(
                ['title' => $c['title'], 'language' => $c['language']],
                [
                    ...$c,
                    'instructor_id' => $instructor?->id,
                ]
            );

            // Modules - language-aware basic structure
            $modulesData = $c['language'] === 'en'
                ? [
                    ['Introduction and theoretical basics', 60],
                    ['Case studies', 120],
                    ['Final assessment', 30],
                ]
                : [
                    ['Intro și bazele teoretice', 60],
                    ['Studii de caz', 120],
                    ['Evaluare finală', 30],
                ];

            foreach ($modulesData as $idx => [$title, $minutes]) {
                CourseModule::updateOrCreate(
                    ['course_id' => $course->id, 'order_index' => $idx + 1],
                    [
                        'title' => $title,
                        'description' => $title,
                        'duration_minutes' => $minutes,
                        'is_mandatory' => true
                    ]
                );
            }

            // Test
            $testTitle = $c['language'] === 'en' ? 'Final Test' : 'Test final';
            $testDesc = $c['language'] === 'en' ? 'Standardized multiple-choice questions' : 'Întrebări grilă standardizate';

            Test::updateOrCreate(
                ['course_id' => $course->id, 'title' => $testTitle],
                [
                    'description' => $testDesc,
                    'passing_score' => $course->passing_score,
                    'time_limit_minutes' => 30,
                    'max_attempts' => $course->max_attempts,
                    'is_required' => true,
                    'questions' => [
                        ['q' => $c['language'] === 'en' ? 'Question 1' : 'Întrebare 1', 'a' => ['a','b','c','d'], 'c' => 1],
                        ['q' => $c['language'] === 'en' ? 'Question 2' : 'Întrebare 2', 'a' => ['a','b','c','d'], 'c' => 2],
                        ['q' => $c['language'] === 'en' ? 'Question 3' : 'Întrebare 3', 'a' => ['a','b','c','d'], 'c' => 3],
                    ]
                ]
            );
        }
    }
}