<?php

namespace Database\Seeders;

use App\Models\MedicalCondition;
use App\Models\User;
use Illuminate\Database\Seeder;

class MedicalConditionSeeder extends Seeder
{
    public function run(): void
    {
        $creator = User::whereHas('roles', fn($q) => $q->where('name', 'professor'))->first()
            ?? User::first();

        // Romanian conditions
        $conditionsRo = [
            [
                'name' => 'Infarct miocardic acut (IMA)',
                'description' => 'Necroza miocardică în urma ischemiei prelungite cauzate de obstrucția coronariană.',
                'icd_10_code' => 'I21.9',
                'icd_11_code' => 'BA41',
                'snomed_ct_code' => '22298006',
                'category' => 'cardiovascular',
                'severity' => 'critical',
                'prevalence' => 1.50,
                'symptoms' => ['durere toracică', 'dispnee', 'diaforeză', 'grețuri'],
                'risk_factors' => ['hiperlipidemie', 'hipertensiune', 'fumat', 'diabet'],
                'complications' => ['aritmii', 'insuficiență cardiacă', 'șoc cardiogen'],
                'differential_diagnosis' => ['embolie pulmonară', 'disecție aortică', 'pericardită'],
                'red_flags' => ['durere toracică >20 min', 'instabilitate hemodinamică'],
                'treatment_approach' => 'MONA, reperfuzie timpurie (PCI primar), beta-blocante, statine.',
                'emergency_management' => 'Activare code STEMI, ECG imediat, acces venos, oxigen dacă SaO2<90%.',
                'chronic_management' => 'DAPT 12 luni, statină intensă, IECA/ARB, control factori de risc.',
                'monitoring_parameters' => ['troponină', 'ECG seriat', 'ecocardiografie'],
                'prognosis' => 'Depinde de timpul până la reperfuzie; mortalitate 5-7% spital.',
                'evidence_level' => 'A',
                'tags' => ['cardiologie', 'urgență', 'STEMI', 'NSTEMI'],
                'sources' => ['ESC Guidelines 2023', 'AHA/ACC 2024'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Pneumonie comunitară',
                'description' => 'Infecție acută a parenchimului pulmonar dobândită în comunitate.',
                'icd_10_code' => 'J18.9',
                'icd_11_code' => 'CA40',
                'snomed_ct_code' => '233604007',
                'category' => 'respiratory',
                'severity' => 'moderate',
                'prevalence' => 5.20,
                'symptoms' => ['febră', 'tuse productivă', 'dispnee', 'durere toracică'],
                'risk_factors' => ['vârstă >65', 'BPOC', 'imunosupresie', 'fumat'],
                'complications' => ['sepsis', 'empiem', 'insuficiență respiratorie'],
                'differential_diagnosis' => ['edem pulmonar', 'embolie pulmonară', 'TB'],
                'red_flags' => ['hipoxie', 'confuzie', 'hipotensiune'],
                'treatment_approach' => 'Antibioterapie empirică, hidratare, oxigenoterapie după necesități.',
                'emergency_management' => 'Scor CRB-65/PSI, decizie spitalizare.',
                'chronic_management' => 'Vaccinare anti-pneumococică/influență, renunțare fumat.',
                'monitoring_parameters' => ['saturație O2', 'CRP', 'hemoculturi în forme severe'],
                'prognosis' => 'Bun în forme ușoare; mortalitate crescută la vârstnici/comorbidități.',
                'evidence_level' => 'A',
                'tags' => ['infecțioase', 'antibiotice', 'ghid'],
                'sources' => ['IDSA/ATS 2019', 'ESCMID'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Diabet zaharat tip 2',
                'description' => 'Tulburare metabolică caracterizată prin hiperglicemie cronică din cauza rezistenței la insulină.',
                'icd_10_code' => 'E11',
                'icd_11_code' => '5A11',
                'snomed_ct_code' => '44054006',
                'category' => 'endocrine',
                'severity' => 'moderate',
                'prevalence' => 9.80,
                'symptoms' => ['polidipsie', 'poliurie', 'polifagie', 'oboseală'],
                'risk_factors' => ['obezitate', 'sedentarism', 'istoric familial'],
                'complications' => ['retinopatie', 'nefropatie', 'cardiopatie ischemică'],
                'differential_diagnosis' => ['diabet tip 1', 'MODY', 'Cushing'],
                'red_flags' => ['cetoacidoză', 'hiperosmolaritate'],
                'treatment_approach' => 'Modificări stil de viață, metformin, GLP-1/SGLT2 în risc CV.',
                'chronic_management' => 'HbA1c la 3-6 luni, control TA/lipide, screening complicații.',
                'monitoring_parameters' => ['HbA1c', 'eGFR', 'microalbuminurie'],
                'prognosis' => 'Depinde de controlul glicemic și comorbidități.',
                'evidence_level' => 'A',
                'tags' => ['metabolism', 'CME'],
                'sources' => ['ADA 2025'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Hipertensiune arterială esențială',
                'description' => 'Creșterea persistentă a tensiunii arteriale fără cauză secundară identificabilă.',
                'icd_10_code' => 'I10',
                'icd_11_code' => 'BA00',
                'snomed_ct_code' => '59621000',
                'category' => 'cardiovascular',
                'severity' => 'moderate',
                'prevalence' => 30.00,
                'symptoms' => ['adesea asimptomatică', 'cefalee', 'amețeli'],
                'risk_factors' => ['vârstă', 'dietă bogată în sare', 'sedentarism'],
                'complications' => ['AVC', 'IMA', 'boală renală cronică'],
                'differential_diagnosis' => ['HTA secundară', 'feocromocitom', 'hiperaldosteronism'],
                'treatment_approach' => 'DASH, reducere sare, IEC/ARA, BCC, diuretice tiazidice.',
                'chronic_management' => 'Monitorizare TA, aderență, modificări stil de viață.',
                'monitoring_parameters' => ['TA domiciliu', 'K/Na', 'funcție renală'],
                'prognosis' => 'Bun cu control adecvat.',
                'evidence_level' => 'A',
                'tags' => ['cardiologie', 'HTA'],
                'sources' => ['ESC/ESH 2023'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Accident vascular cerebral ischemic',
                'description' => 'Deficit neurologic acut datorat ocluziei arteriale cerebrale.',
                'icd_10_code' => 'I63.9',
                'icd_11_code' => '8B11',
                'snomed_ct_code' => '422504002',
                'category' => 'neurological',
                'severity' => 'critical',
                'prevalence' => 2.50,
                'symptoms' => ['hemipareză', 'afazie', 'hemianopsie', 'debut brusc'],
                'risk_factors' => ['FA', 'HTA', 'diabet', 'ateroscleroză'],
                'complications' => ['edem cerebral', 'hemoragie', 'aspirație'],
                'differential_diagnosis' => ['hipoglicemie', 'migrenă', 'crize epileptice'],
                'red_flags' => ['fereastră terapeutică', 'semne de herniere'],
                'treatment_approach' => 'tPA în fereastră, trombectomie mecanică, control TA.',
                'emergency_management' => 'CT fără contrast urgent, scor NIHSS.',
                'chronic_management' => 'Prevenție secundară: antiagregante/anticoagulare, control factori risc.',
                'monitoring_parameters' => ['TA', 'glucoză', 'imagistică repetată dacă necesar'],
                'prognosis' => 'Variabil; depinde de timp și localizare.',
                'evidence_level' => 'A',
                'tags' => ['neurologie', 'urgență'],
                'sources' => ['ESO 2024'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Insuficiență cardiacă cu fracție de ejecție redusă (HFrEF)',
                'description' => 'Sindrom clinic caracterizat prin simptome și semne de congestie și perfuzie inadecvată cu FE <40%.',
                'icd_10_code' => 'I50.2',
                'icd_11_code' => 'BD10',
                'snomed_ct_code' => '84114007',
                'category' => 'cardiovascular',
                'severity' => 'severe',
                'prevalence' => 2.00,
                'symptoms' => ['dispnee', 'edeme periferice', 'ortopnee', 'oboseală'],
                'risk_factors' => ['IMA', 'HTA', 'DZ', 'valvulopatii'],
                'complications' => ['aritmii', 'edem pulmonar', 'insuficiență renală'],
                'differential_diagnosis' => ['BPOC', 'embolie pulmonară', 'pneumonie'],
                'red_flags' => ['hipotensiune', 'hipoxie severă', 'oligurie'],
                'treatment_approach' => 'IECA/ARA, beta-blocant, MRA, SGLT2, diuretice, device-uri după indicații.',
                'emergency_management' => 'Diuretice i.v., oxigen/NIV, vasodilatatoare dacă TA permite.',
                'chronic_management' => 'Optimizare GDMT, educație, telemonitorizare, reabilitare.',
                'monitoring_parameters' => ['NT-proBNP', 'TA', 'funcție renală', 'K+'],
                'prognosis' => 'Mortalitate anuală semnificativă; îmbunătățită de GDMT.',
                'evidence_level' => 'A',
                'tags' => ['cardiologie', 'insuficiență cardiacă', 'GDMT'],
                'sources' => ['ESC HF 2023'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Exacerbare acută BPOC',
                'description' => 'Agravarea acută a simptomelor respiratorii peste variabilitatea zilnică în BPOC.',
                'icd_10_code' => 'J44.1',
                'icd_11_code' => 'CA22',
                'snomed_ct_code' => '195951007',
                'category' => 'respiratory',
                'severity' => 'moderate',
                'prevalence' => 4.00,
                'symptoms' => ['dispnee', 'tuse', 'sputa purulentă', 'wheezing'],
                'risk_factors' => ['fumat', 'infecții', 'poluare'],
                'complications' => ['insuficiență respiratorie', 'pneumonie'],
                'differential_diagnosis' => ['astm', 'IC', 'embolie pulmonară'],
                'red_flags' => ['hipercapnie', 'acidoză', 'alterarea stării mentale'],
                'treatment_approach' => 'Bronhodilatatoare, corticosteroizi, antibiotice dacă purulență, NIV după necesități.',
                'emergency_management' => 'Gazometrie, oxigen titrat la SaO2 88-92%, NIV dacă necesar.',
                'chronic_management' => 'Renunțare la fumat, vaccinări, bronhodilatatoare, reabilitare.',
                'monitoring_parameters' => ['saturație O2', 'PaCO2', 'pH', 'VEMS (în stabilitate)'],
                'prognosis' => 'Risc de recurență; depinde de severitate și aderență.',
                'evidence_level' => 'A',
                'tags' => ['pulmonologie', 'NIV'],
                'sources' => ['GOLD 2024'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Tromboembolism pulmonar (TEP)',
                'description' => 'Obstrucția arterelor pulmonare prin trombi migrați din sistemul venos.',
                'icd_10_code' => 'I26.9',
                'icd_11_code' => 'BD20',
                'snomed_ct_code' => '59282003',
                'category' => 'cardiovascular',
                'severity' => 'severe',
                'prevalence' => 0.60,
                'symptoms' => ['dispnee bruscă', 'durere toracică pleuritică', 'tahicardie', 'hemoptizie'],
                'risk_factors' => ['TVP', 'chirurgie recentă', 'imobilizare', 'cancer'],
                'complications' => ['HTP cronică tromboembolică', 'moarte subită'],
                'differential_diagnosis' => ['IMA', 'pneumonie', 'pneumotorax'],
                'red_flags' => ['instabilitate hemodinamică', 'hipoxie severă'],
                'treatment_approach' => 'Anticoagulare, tromboliză în instabili, considerare embolectomie.',
                'emergency_management' => 'Scor Wells, D-dimer, angio-CT, heparină inițial.',
                'chronic_management' => 'Anticoagulare 3-6 luni sau pe termen lung în funcție de risc.',
                'monitoring_parameters' => ['SaO2', 'INR/anti-Xa', 'semne de sângerare'],
                'prognosis' => 'Bun sub tratament, rezervat în forme masive.',
                'evidence_level' => 'A',
                'tags' => ['tromboză', 'anticoagulare'],
                'sources' => ['ESC PE 2019'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Boală cronică de rinichi stadiul 3',
                'description' => 'Afectare renală cronică cu eGFR 30-59 ml/min/1.73m².',
                'icd_10_code' => 'N18.3',
                'icd_11_code' => 'GC50.3',
                'snomed_ct_code' => '433144002',
                'category' => 'nephrology',
                'severity' => 'moderate',
                'prevalence' => 8.00,
                'symptoms' => ['adesea asimptomatică', 'edeme', 'nocturie'],
                'risk_factors' => ['diabet', 'HTA', 'vârstă'],
                'complications' => ['anemie', 'boală mineral-osoasă', 'hiperkaliemie'],
                'differential_diagnosis' => ['IRA', 'nefropatii specifice'],
                'red_flags' => ['hiperkaliemie severă', 'edem pulmonar'],
                'treatment_approach' => 'Control TA, inhibitor SGLT2, corecție factori de risc.',
                'chronic_management' => 'Monitorizare eGFR/albuminurie, dietă, tratament anemie.',
                'monitoring_parameters' => ['eGFR', 'K+', 'Hb', 'albuminurie'],
                'prognosis' => 'Progresivă; încetinirea progresiei este posibilă.',
                'evidence_level' => 'A',
                'tags' => ['nefrologie', 'SGLT2'],
                'sources' => ['KDIGO 2024'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Anemie feriprivă',
                'description' => 'Anemie datorată deficitului de fier, frecvent prin pierderi cronice.',
                'icd_10_code' => 'D50.9',
                'icd_11_code' => '3A00',
                'snomed_ct_code' => '87522002',
                'category' => 'hematology',
                'severity' => 'mild',
                'prevalence' => 20.00,
                'symptoms' => ['oboseală', 'dispnee de efort', 'paloare', 'tahicardie'],
                'risk_factors' => ['menoragii', 'boală GI', 'dietă săracă în fier'],
                'complications' => ['toleranță redusă la efort', 'afectare cognitivă'],
                'differential_diagnosis' => ['anemie cronică', 'talasemie', 'deficit B12'],
                'red_flags' => ['sângerare ocultă', 'scădere ponderală'],
                'treatment_approach' => 'Fier oral/parenteral, tratarea cauzei.',
                'emergency_management' => 'Transfuzie dacă instabil sau Hb foarte scăzut.',
                'chronic_management' => 'Monitorizare feritină, MCV, Hb.',
                'monitoring_parameters' => ['Hb', 'feritină', 'saturație transferină'],
                'prognosis' => 'Bun cu tratament adecvat.',
                'evidence_level' => 'A',
                'tags' => ['hematologie'],
                'sources' => ['BCSH 2021'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Pancreatită acută',
                'description' => 'Inflamație acută a pancreasului, de obicei legată de litiază biliară sau alcool.',
                'icd_10_code' => 'K85.9',
                'icd_11_code' => 'DD52',
                'snomed_ct_code' => '197456007',
                'category' => 'gastroenterology',
                'severity' => 'severe',
                'prevalence' => 0.05,
                'symptoms' => ['durere epigastrică severă', 'grețuri', 'vărsături'],
                'risk_factors' => ['litiază biliară', 'alcool', 'hipertrigliceridemie'],
                'complications' => ['necroză pancreatică', 'șoc', 'insuficiență multiorgan'],
                'differential_diagnosis' => ['ulcer perforat', 'colangită', 'AAA rupt'],
                'red_flags' => ['instabilitate hemodinamică', 'insuficiență respiratorie'],
                'treatment_approach' => 'Resuscitare volemică, analgezie, suport nutrițional, ERCP dacă colangită.',
                'emergency_management' => 'Scor severitate (Ranson/BISAP), CT dacă necesar.',
                'chronic_management' => 'Adresarea cauzei, abstinență alcool, tratament litiază.',
                'monitoring_parameters' => ['amilază/lipază', 'CRP', 'imagistică'],
                'prognosis' => 'Variabil; bună în forme ușoare, severă în forme necrotice.',
                'evidence_level' => 'A',
                'tags' => ['gastro', 'urgență'],
                'sources' => ['IAP/APA 2013 update'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Colecistită acută',
                'description' => 'Inflamație acută a vezicii biliare, de obicei asociată cu calculi.',
                'icd_10_code' => 'K81.0',
                'icd_11_code' => 'DD55',
                'snomed_ct_code' => '65275009',
                'category' => 'gastroenterology',
                'severity' => 'moderate',
                'prevalence' => 0.30,
                'symptoms' => ['durere hipocondrul drept', 'febră', 'greață'],
                'risk_factors' => ['femei', 'vârstă', 'obezitate', 'sarcină'],
                'complications' => ['empiem vezicular', 'perforație', 'sepsis'],
                'differential_diagnosis' => ['colangită', 'ulcer duodenal', 'hepatită'],
                'red_flags' => ['icter', 'semne de sepsis'],
                'treatment_approach' => 'Antibiotice, colecistectomie precoce.',
                'emergency_management' => 'Ecografie, scor Tokyo, drenaj dacă necesar.',
                'chronic_management' => 'Chirurgie electivă dacă nu s-a efectuat.',
                'monitoring_parameters' => ['CRP', 'leucocite', 'imagistică'],
                'prognosis' => 'Bun cu tratament.',
                'evidence_level' => 'A',
                'tags' => ['chirurgie', 'biliar'],
                'sources' => ['Tokyo Guidelines 2018'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Apendicită acută',
                'description' => 'Inflamație acută a apendicelui vermiform.',
                'icd_10_code' => 'K35.8',
                'icd_11_code' => 'DB61',
                'snomed_ct_code' => '74400008',
                'category' => 'surgery',
                'severity' => 'moderate',
                'prevalence' => 0.10,
                'symptoms' => ['durere FID', 'febră', 'anorexie', 'greață'],
                'risk_factors' => ['vârstă tânără'],
                'complications' => ['peritonită', 'abces'],
                'differential_diagnosis' => ['GEC', 'colică renală', 'boală inflamatorie intestinală'],
                'red_flags' => ['semne peritoneale', 'sepsis'],
                'treatment_approach' => 'Apendicectomie, antibiotice.',
                'emergency_management' => 'Scor Alvarado/AIR, ecografie/CT.',
                'chronic_management' => 'Îngrijire postoperatorie.',
                'monitoring_parameters' => ['CRP', 'leucocite'],
                'prognosis' => 'Excelent după chirurgie.',
                'evidence_level' => 'A',
                'tags' => ['chirurgie', 'urgență'],
                'sources' => ['WSES 2020'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Infecție urinară necomplicată',
                'description' => 'Infecție bacteriană a tractului urinar inferior fără complicații structurale.',
                'icd_10_code' => 'N39.0',
                'icd_11_code' => 'GB61',
                'snomed_ct_code' => '68566005',
                'category' => 'infectious_diseases',
                'severity' => 'mild',
                'prevalence' => 10.00,
                'symptoms' => ['disurie', 'polakiurie', 'urgenta micțională'],
                'risk_factors' => ['femei', 'activitate sexuală', 'postmenopauză'],
                'complications' => ['pielonefrită'],
                'differential_diagnosis' => ['vaginită', 'uretrită'],
                'red_flags' => ['febră', 'flanc pain'],
                'treatment_approach' => 'Antibiotice conform ghid, hidratare.',
                'chronic_management' => 'Profilaxie la recidive, modificări comportamentale.',
                'monitoring_parameters' => ['urocultură dacă recidive'],
                'prognosis' => 'Excelent.',
                'evidence_level' => 'A',
                'tags' => ['urologie', 'infecțios'],
                'sources' => ['EAU 2023'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Pielonefrită acută',
                'description' => 'Infecție bacteriană a parenchimului renal.',
                'icd_10_code' => 'N10',
                'icd_11_code' => 'GB41',
                'snomed_ct_code' => '45816000',
                'category' => 'infectious_diseases',
                'severity' => 'moderate',
                'prevalence' => 0.30,
                'symptoms' => ['febră', 'frison', 'durere lombară', 'disurie'],
                'risk_factors' => ['sex feminin', 'anomalii urinare', 'cateterizare'],
                'complications' => ['sepsis', 'absces renal'],
                'differential_diagnosis' => ['colică renală', 'apendicită', 'BCR acut'],
                'red_flags' => ['instabilitate hemodinamică', 'sepsis'],
                'treatment_approach' => 'Antibiotice i.v./oral, drenaj dacă obstructiv.',
                'emergency_management' => 'Urocultură, ecografie, CT la cazuri severe.',
                'chronic_management' => 'Profilaxie și investigare anomalii.',
                'monitoring_parameters' => ['urocultură de control'],
                'prognosis' => 'Bun cu tratament.',
                'evidence_level' => 'A',
                'tags' => ['nefro-urologie', 'infecțios'],
                'sources' => ['EAU 2023'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Tulburare depresivă majoră',
                'description' => 'Tulburare afectivă caracterizată prin dispoziție depresivă și anhedonie ≥2 săptămâni.',
                'icd_10_code' => 'F32.9',
                'icd_11_code' => '6A70',
                'snomed_ct_code' => '35489007',
                'category' => 'psychiatry',
                'severity' => 'moderate',
                'prevalence' => 6.00,
                'symptoms' => ['tristețe', 'anhedonie', 'insomnie', 'idei de inutilitate'],
                'risk_factors' => ['istoric familial', 'stres', 'boală cronică'],
                'complications' => ['suicid', 'abuz de substanțe'],
                'differential_diagnosis' => ['tulburare bipolară', 'distimie', 'hipotiroidism'],
                'red_flags' => ['idei suicidare', 'psihoză'],
                'treatment_approach' => 'Psihoterapie, ISRS/ISRN, ECT/TMS în forme rezistente.',
                'chronic_management' => 'Monitorizare recăderi, suport psihosocial.',
                'monitoring_parameters' => ['PHQ-9', 'adherență', 'efecte adverse'],
                'prognosis' => 'Variabil; bună cu tratament adecvat.',
                'evidence_level' => 'A',
                'tags' => ['psihiatrie'],
                'sources' => ['APA 2023'],
                'status' => 'published',
                'language' => 'ro'
            ],
            [
                'name' => 'Astmul bronșic - criză',
                'description' => 'Exacerbare acută a simptomelor de astm cu bronhospasm și inflamație.',
                'icd_10_code' => 'J45.9',
                'icd_11_code' => 'CA23',
                'snomed_ct_code' => '195967001',
                'category' => 'respiratory',
                'severity' => 'moderate',
                'prevalence' => 5.00,
                'symptoms' => ['dispnee', 'wheezing', 'tuse', 'opresiune toracică'],
                'risk_factors' => ['alergeni', 'infecții', 'efort'],
                'complications' => ['insuficiență respiratorie'],
                'differential_diagnosis' => ['BPOC', 'TEP', 'IC'],
                'red_flags' => ['silence toracic', 'hipercapnie'],
                'treatment_approach' => 'SABA repetat, corticosteroid sistemic, O2, MgSO4 i.v. la sever.',
                'emergency_management' => 'PEF/FEV1, gazometrie, NIV în cazuri selectate.',
                'chronic_management' => 'Ghid GINA: ICS/LABA, evitarea triggerilor.',
                'monitoring_parameters' => ['PEF', 'simptome', 'utilizare SABA'],
                'prognosis' => 'Bun cu control adecvat.',
                'evidence_level' => 'A',
                'tags' => ['pulmonologie', 'GINA'],
                'sources' => ['GINA 2024'],
                'status' => 'published',
                'language' => 'ro'
            ],
        ];

        // English conditions (selected set and translations)
        $conditionsEn = [
            [
                'name' => 'Acute Myocardial Infarction (AMI)',
                'description' => 'Myocardial necrosis due to prolonged ischemia from coronary occlusion.',
                'icd_10_code' => 'I21.9',
                'icd_11_code' => 'BA41',
                'snomed_ct_code' => '22298006',
                'category' => 'cardiovascular',
                'severity' => 'critical',
                'prevalence' => 1.50,
                'symptoms' => ['chest pain', 'dyspnea', 'diaphoresis', 'nausea'],
                'risk_factors' => ['hyperlipidemia', 'hypertension', 'smoking', 'diabetes'],
                'complications' => ['arrhythmias', 'heart failure', 'cardiogenic shock'],
                'differential_diagnosis' => ['pulmonary embolism', 'aortic dissection', 'pericarditis'],
                'red_flags' => ['chest pain >20 min', 'hemodynamic instability'],
                'treatment_approach' => 'MONA, early reperfusion (primary PCI), beta-blockers, statins.',
                'emergency_management' => 'Activate STEMI code, immediate ECG, IV access, oxygen if SaO2<90%.',
                'chronic_management' => 'DAPT 12 months, high-intensity statin, ACEi/ARB, risk factor control.',
                'monitoring_parameters' => ['troponin', 'serial ECG', 'echocardiography'],
                'prognosis' => 'Depends on time to reperfusion; in-hospital mortality 5-7%.',
                'evidence_level' => 'A',
                'tags' => ['cardiology', 'emergency', 'STEMI', 'NSTEMI'],
                'sources' => ['ESC Guidelines 2023', 'AHA/ACC 2024'],
                'status' => 'published',
                'language' => 'en'
            ],
            [
                'name' => 'Community-Acquired Pneumonia',
                'description' => 'Acute infection of the lung parenchyma acquired outside the hospital.',
                'icd_10_code' => 'J18.9',
                'icd_11_code' => 'CA40',
                'snomed_ct_code' => '233604007',
                'category' => 'respiratory',
                'severity' => 'moderate',
                'prevalence' => 5.20,
                'symptoms' => ['fever', 'productive cough', 'dyspnea', 'pleuritic chest pain'],
                'risk_factors' => ['age >65', 'COPD', 'immunosuppression', 'smoking'],
                'complications' => ['sepsis', 'empyema', 'respiratory failure'],
                'differential_diagnosis' => ['pulmonary edema', 'pulmonary embolism', 'TB'],
                'red_flags' => ['hypoxia', 'confusion', 'hypotension'],
                'treatment_approach' => 'Empiric antibiotics, hydration, oxygen as needed.',
                'emergency_management' => 'CRB-65/PSI scoring, hospitalization decision.',
                'chronic_management' => 'Pneumococcal/influenza vaccination, smoking cessation.',
                'monitoring_parameters' => ['O2 saturation', 'CRP', 'blood cultures in severe cases'],
                'prognosis' => 'Good in mild cases; higher mortality in elderly/comorbidities.',
                'evidence_level' => 'A',
                'tags' => ['infectious', 'antibiotics', 'guideline'],
                'sources' => ['IDSA/ATS 2019', 'ESCMID'],
                'status' => 'published',
                'language' => 'en'
            ],
            [
                'name' => 'Type 2 Diabetes Mellitus',
                'description' => 'Metabolic disorder characterized by chronic hyperglycemia due to insulin resistance.',
                'icd_10_code' => 'E11',
                'icd_11_code' => '5A11',
                'snomed_ct_code' => '44054006',
                'category' => 'endocrine',
                'severity' => 'moderate',
                'prevalence' => 9.80,
                'symptoms' => ['polydipsia', 'polyuria', 'polyphagia', 'fatigue'],
                'risk_factors' => ['obesity', 'sedentary lifestyle', 'family history'],
                'complications' => ['retinopathy', 'nephropathy', 'ischemic heart disease'],
                'differential_diagnosis' => ['type 1 diabetes', 'MODY', 'Cushing syndrome'],
                'red_flags' => ['ketoacidosis', 'hyperosmolar state'],
                'treatment_approach' => 'Lifestyle modification, metformin, GLP-1/SGLT2 in CV risk.',
                'chronic_management' => 'HbA1c every 3-6 months, BP/lipids control, complications screening.',
                'monitoring_parameters' => ['HbA1c', 'eGFR', 'microalbuminuria'],
                'prognosis' => 'Depends on glycemic control and comorbidities.',
                'evidence_level' => 'A',
                'tags' => ['metabolism', 'CME'],
                'sources' => ['ADA 2025'],
                'status' => 'published',
                'language' => 'en'
            ],
            [
                'name' => 'Hypertension (Primary)',
                'description' => 'Persistent elevation of blood pressure without a secondary cause.',
                'icd_10_code' => 'I10',
                'icd_11_code' => 'BA00',
                'snomed_ct_code' => '59621000',
                'category' => 'cardiovascular',
                'severity' => 'moderate',
                'prevalence' => 30.00,
                'symptoms' => ['often asymptomatic', 'headache', 'dizziness'],
                'risk_factors' => ['age', 'high-salt diet', 'sedentary lifestyle'],
                'complications' => ['stroke', 'MI', 'chronic kidney disease'],
                'differential_diagnosis' => ['secondary HTN', 'pheochromocytoma', 'hyperaldosteronism'],
                'red_flags' => ['hypertensive emergency'],
                'treatment_approach' => 'DASH, salt restriction, ACEi/ARB, CCB, thiazide diuretics.',
                'chronic_management' => 'Home BP monitoring, adherence, lifestyle changes.',
                'monitoring_parameters' => ['home BP', 'K/Na', 'renal function'],
                'prognosis' => 'Good with adequate control.',
                'evidence_level' => 'A',
                'tags' => ['cardiology', 'HTN'],
                'sources' => ['ESC/ESH 2023'],
                'status' => 'published',
                'language' => 'en'
            ],
            [
                'name' => 'Ischemic Stroke',
                'description' => 'Acute neurological deficit due to arterial occlusion.',
                'icd_10_code' => 'I63.9',
                'icd_11_code' => '8B11',
                'snomed_ct_code' => '422504002',
                'category' => 'neurological',
                'severity' => 'critical',
                'prevalence' => 2.50,
                'symptoms' => ['hemiparesis', 'aphasia', 'hemianopia', 'sudden onset'],
                'risk_factors' => ['AF', 'HTN', 'diabetes', 'atherosclerosis'],
                'complications' => ['cerebral edema', 'hemorrhage', 'aspiration'],
                'differential_diagnosis' => ['hypoglycemia', 'migraine', 'seizures'],
                'red_flags' => ['therapeutic window', 'signs of herniation'],
                'treatment_approach' => 'tPA within window, mechanical thrombectomy, BP control.',
                'emergency_management' => 'Non-contrast CT urgently, NIHSS score.',
                'chronic_management' => 'Secondary prevention: antiplatelets/anticoagulation, risk factor control.',
                'monitoring_parameters' => ['BP', 'glucose', 'repeat imaging if needed'],
                'prognosis' => 'Variable; depends on time and location.',
                'evidence_level' => 'A',
                'tags' => ['neurology', 'emergency'],
                'sources' => ['ESO 2024'],
                'status' => 'published',
                'language' => 'en'
            ],
            [
                'name' => 'Acute Exacerbation of COPD',
                'description' => 'Acute worsening of respiratory symptoms beyond normal day-to-day variation in COPD.',
                'icd_10_code' => 'J44.1',
                'icd_11_code' => 'CA22',
                'snomed_ct_code' => '195951007',
                'category' => 'respiratory',
                'severity' => 'moderate',
                'prevalence' => 4.00,
                'symptoms' => ['dyspnea', 'cough', 'purulent sputum', 'wheezing'],
                'risk_factors' => ['smoking', 'infections', 'pollution'],
                'complications' => ['respiratory failure', 'pneumonia'],
                'differential_diagnosis' => ['asthma', 'HF', 'PE'],
                'red_flags' => ['hypercapnia', 'acidosis', 'altered mentation'],
                'treatment_approach' => 'Bronchodilators, systemic steroids, antibiotics if purulence, NIV as needed.',
                'emergency_management' => 'ABG, titrated O2 to SaO2 88-92%, NIV if required.',
                'chronic_management' => 'Smoking cessation, vaccinations, bronchodilators, rehab.',
                'monitoring_parameters' => ['O2 saturation', 'PaCO2', 'pH'],
                'prognosis' => 'Risk of recurrence; depends on severity and adherence.',
                'evidence_level' => 'A',
                'tags' => ['pulmonology', 'NIV'],
                'sources' => ['GOLD 2024'],
                'status' => 'published',
                'language' => 'en'
            ],
        ];

        foreach ($conditionsRo as $data) {
            $data['created_by'] = $creator?->id;
            MedicalCondition::updateOrCreate(
                ['name' => $data['name'], 'language' => $data['language']],
                $data
            );
        }

        foreach ($conditionsEn as $data) {
            $data['created_by'] = $creator?->id;
            MedicalCondition::updateOrCreate(
                ['name' => $data['name'], 'language' => $data['language']],
                $data
            );
        }
    }
}