global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: []
  - job_name: 'php-fpm'
    static_configs:
      - targets: []